export const PAGE_TITLE_SET = 'PAGE_TITLE_SET';
export const PAGE_CONTENT_SET = 'PAGE_CONTENT_SET';
export const NAVBAR_ITEM_SET = 'NAVBAR_ITEM_SET';
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL"

// FEED FIREBASE PRODUCTS
export const BEGIN_PRODUCTS_FEED = "BEGIN_PRODUCTS_FEED";
export const SUCCESS_PRODUCTS_FEED = "SUCCESS_PRODUCTS_FEED";
export const FAIL_PRODUCTS_FEED = "FAIL_PRFAIL_PRODUCTS_FEEDODUCTS_REQUEST";

// REQUEST FIREBASE PRODUCTS
export const BEGIN_PRODUCTS_REQUEST = "BEGIN_PRODUCTS_REQUEST";
export const SUCCESS_PRODUCTS_REQUEST = "SUCCESS_PRODUCTS_REQUEST";
export const FAIL_PRODUCTS_REQUEST = "FAIL_PRODUCTS_REQUEST";